services:
  postgres:
    image: postgres:18
    container_name: investimentes_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/postgreSQL/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

volumes:
  postgres_data:
